### PR TITLE
Fix #23, fix #33: close uploadStub when closing PhotosLibraryClient

### LINKED ISSUE #23: Exception when creating client
Working on desktop application working with google photos. Sometimes having an exception:
```
Oct 24, 2019 5:22:06 PM io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference cleanQueue
SEVERE: *~*~*~ Channel ManagedChannelImpl{logId=17, target=photoslibrary.googleapis.com:443} was not shutdown properly!!! ~*~*~*
    Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
java.lang.RuntimeException: ManagedChannel allocation site
	at io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference.<init>(ManagedChannelOrphanWrapper.java:94)
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:52)
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:43)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:514)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel(InstantiatingGrpcChannelProvider.java:223)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createChannel(InstantiatingGrpcChannelProvider.java:164)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.getTransportChannel(InstantiatingGrpcChannelProvider.java:156)
	at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:157)
	at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:122)
	at com.google.photos.library.v1.upload.PhotosLibraryUploadStubImpl.<init>(PhotosLibraryUploadStubImpl.java:35)
	at com.google.photos.library.v1.upload.PhotosLibraryUploadStubImpl.createStub(PhotosLibraryUploadStubImpl.java:44)
	at com.google.photos.library.v1.PhotosLibraryClient.<init>(PhotosLibraryClient.java:103)
	at com.google.photos.library.v1.PhotosLibraryClient.initialize(PhotosLibraryClient.java:114)
	at org.hurricup.google.PhotosLibraryClientFactory.createClient(PhotosLibraryClientFactory.java:64)
```

### LINKED ISSUE #33: PhotosLibraryClient close failing
When calling photosLibraryClient.close() I'm getting the below exception frequently. Any reason why?Running 
```
Try.run(() -> photosLibraryClientFinal.shutdownNow());
Try.run(() -> photosLibraryClientFinal.awaitTermination(30, TimeUnit.SECONDS));
Try.run(() -> photosLibraryClientFinal.close());
```
does not seem to help as well. Please share your thoughts on how to fix this issue?

```
21:30:05 c.b.p.m.GooglePhotosSlideshow - Closing photos client now
21:30:05 i.g.i.ManagedChannelOrphanWrapper - *~*~*~ Channel ManagedChannelImpl{logId=3, target=photoslibrary.googleapis.com:443} was not shutdown properly!!! ~*~*~*
    Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
java.lang.RuntimeException: ManagedChannel allocation site
	at io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference.<init>(ManagedChannelOrphanWrapper.java:94)
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:52)
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:43)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:548)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel(InstantiatingGrpcChannelProvider.java:304)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.access$1500(InstantiatingGrpcChannelProvider.java:71)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider$1.createSingleChannel(InstantiatingGrpcChannelProvider.java:202)
	at com.google.api.gax.grpc.ChannelPool.create(ChannelPool.java:72)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createChannel(InstantiatingGrpcChannelProvider.java:209)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.getTransportChannel(InstantiatingGrpcChannelProvider.java:192)
	at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:155)
	at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:122)
	at com.google.photos.library.v1.upload.PhotosLibraryUploadStubImpl.<init>(PhotosLibraryUploadStubImpl.java:35)
	at com.google.photos.library.v1.upload.PhotosLibraryUploadStubImpl.createStub(PhotosLibraryUploadStubImpl.java:44)
	at com.google.photos.library.v1.PhotosLibraryClient.<init>(PhotosLibraryClient.java:103)
	at com.google.photos.library.v1.PhotosLibraryClient.initialize(PhotosLibraryClient.java:114)
	at com.bala.pi.module.GooglePhotosSlideshow.refreshGooglePhotoData(Unknown Source)
	at com.bala.pi.module.GooglePhotosSlideshow.checkIfDeviceOnlineAndRefreshGPhotoMetadata(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:741)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)
	at com.bala.pi.module.GooglePhotosSlideshow$$EnhancerBySpringCGLIB$$a312e5d2.checkIfDeviceOnlineAndRefreshGPhotoMetadata(<generated>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:305)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:835)
```

### PR DESCRIPTION
**Pull request by mixin82**

### CODE REVIEW

File: photoslibraryapi/src/main/java/com/google/photos/library/v1/internal/InternalPhotosLibraryClient.java [hunk 1]
```diff
@@ -1884,7 +1884,7 @@ public final MediaItem updateMediaItem(UpdateMediaItemRequest request) {
   }
 
   @Override
```
Comment (jfschmakeit) [inline photoslibraryapi/src/main/java/com/google/photos/library/v1/internal/InternalPhotosLibraryClient.java:1886]: Unfortunately the classes in the `internal` package are technically autogenerated before being published here, so it's a bit harder to update this class and we need to consider this carefully. 

@katmle - What do you think about this proposal? I can't quite think of a better way to address this either.

**Review by jfschmakeit — COMMENTED** [review]
Thanks for this pull request, this looks like it addresses the issues.

There are a few complications around changing a class in the `internal` package (and in particular change the signature of a method there), so we need to consider this carefully. I'm following up on this and will keep you posted.

File: photoslibraryapi/src/main/java/com/google/photos/library/v1/internal/InternalPhotosLibraryClient.java (hunk 1 above)
Comment (mixin82) [reply photoslibraryapi/src/main/java/com/google/photos/library/v1/internal/InternalPhotosLibraryClient.java:1886]: I noticed that too but I can't think of any good reason to keep the close() "final" in the first place. I wonder if we could raise a CR to the gapic-generator maybe?

Comment (jfschmakeit) [reply photoslibraryapi/src/main/java/com/google/photos/library/v1/internal/InternalPhotosLibraryClient.java:1886]: @mixin82 Yes, after some more discussions the best way forward here is to see if we can submit this as a feature request to the gapic generator. 

(There are a few other changes on our end in the works that might also impact this - we are still using a slightly different generator and need to switch over first.) I'll file a feature request in the next few days once we have confirmed some additional details on our end.

In the meantime we might be able to submit this as-is and spin up a new release with this change. Stay tuned, we'll do a little more testing to make sure there aren't any other unintended side effects.

File: photoslibraryapi/src/main/java/com/google/photos/library/v1/PhotosLibraryClient.java [hunk 2]
```diff
@@ -319,4 +319,15 @@ public final ListMediaItemsPagedResponse listMediaItems() {
   public final ListSharedAlbumsPagedResponse listSharedAlbums() {
     return super.listSharedAlbums(false);
   }
+
+  @Override
+  public void close() {
+    super.close();
+    try {
+      uploadStub.close();
+    } catch (Exception e) {
```
Comment (mixin82) [inline photoslibraryapi/src/main/java/com/google/photos/library/v1/PhotosLibraryClient.java:328]: While it is true that `BackgroundResourceAggregation.shutdown()` doesn't throw checked exceptions, it could throw `RuntimeException` ones though. I could maybe filter those ones and re-throw them without the need to change the `InternalPhotosLibraryClient.close()` signature. Also, I don’t think the removal of the `throw Exception` in  `BackgroundResource.close()` will happen any time soon since there hasn’t been a new major version upgrade in 3 years. I suppose it's quite unlikely they are going to introduce a checked exception for  `BackgroundResourceAggregation.shutdown()`, but if that happens this change will silently ignore it. A workaround for both issues that allows to capture any Exception without the need to modify the signature could be to do just this:
```java
try {
￼    uploadStub.close();
￼} catch (Exception e) {
   throw new RuntimeException(e);
}
```
What's your opinion on this @jfschmakeit ?

Comment (jfschmakeit) [reply photoslibraryapi/src/main/java/com/google/photos/library/v1/PhotosLibraryClient.java:328]: Yes, this is an interesting one. (There does seem to be a bit of a mismatch further in the gapic/autogenerated side.)

I think we should not silently catch exceptions, even if they are unlikely to occur. FWIW, if the checked exception is ever removed from `BackgroundResource.close()`, this would come up as a major breaking change that we can handle at the same time.

I think the cleanest way to handle this is actually your final proposal - leaving the method signature as-is and rethrowing the exception as a `RuntimeException`. This follows the spirit of the underlying exception that would be thrown from `uploadStub.close()` and is also similar to the way this is handled by the `InternalPhotosLibraryClient`. Given there are no guarantees on the type of Exception, this might be the best approach.

**Comment by jfschmakeit** [comment]
I have just filed a request with the gapic team here: https://github.com/googleapis/gapic-generator-java/issues/650

In the meantime we should be able to submit this and roll this into a new release. Please stay tuned.

**Review by jfschmakeit — CHANGES_REQUESTED** [review]
Unfortunately this is currently not passing the tests, please make sure to format the changed files again:

> The following files are not formatted properly:
> 
> photoslibraryapi/src/main/java/com/google/photos/library/v1/PhotosLibraryClient.java
> :photoslibraryapi:verifyGoogleJavaFormat (Thread[Execution worker for ':',5,main]) completed. Took 0.017 secs.
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':photoslibraryapi:verifyGoogleJavaFormat'.
> > Problems: formatting style violations
> 

Run the gradle task `test`(or the `:photoslibraryapi:verifyGoogleJavaFormat` task) to verify your change. 
You can automatically format the files using the `googleJavaFormat` gradle task.

Once you have addressed this we can merge it and make it a new release.

Thanks!

**Comment by mixin82** [comment]
Apologies @jfschmakeit, I thought I changed my column width...I should have checked anyway. Should be good now.
Thanks

**Comment by jfschmakeit** [comment]
Great - thanks for bearing with me through the review! We are all good to merge this into a new release.

(Unfortunately the gapic team isn't going to take our proposal on board, so we'll have to do some pre-processing on our end. We can merge this manual change in for now and update our pipeline to include this in the future.)

**Review by jfschmakeit — APPROVED** [review]
